[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "public"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
